import { z } from 'zod';
import {
  BookingResponseSchema,
  CreateBookingRequestSchema,
  UpdateBookingStatusRequestSchema,
  CreateCustomerRequestSchema,
  CustomerResponseSchema,
  CustomerDetailResponseSchema,
  CustomerImportCommitRequestSchema,
  CustomerImportCommitResponseSchema,
  CustomerImportPreviewRequestSchema,
  CustomerImportPreviewResponseSchema,
  CreateInteractionRequestSchema,
  InteractionResponseSchema,
  RecordConsentRequestSchema,
  UpdateCustomerRequestSchema,
  ErrorResponseSchema,
  RegisterRequestSchema,
  RegisterResponseSchema,
  ResultsResponseSchema,
  SignInRequestSchema,
  PasswordResetRequestSchema,
  PasswordResetRequestResponseSchema,
  PasswordResetCompleteRequestSchema,
  PasswordResetCompleteResponseSchema,
  TodayResponseSchema,
  CsrfResponseSchema,
  WorkspaceResponseSchema,
  WorkspaceSettingsPatchSchema,
  ReviewListQuerySchema,
  ReviewListResponseSchema,
  CreateReviewRequestSchema,
  ReviewResponseSchema,
  ReviewResponseActionSchema,
  ReviewImportPreviewRequestSchema,
  ReviewImportPreviewResponseSchema,
  ReviewImportCommitRequestSchema,
  ReviewImportCommitResponseSchema,
  ResultsQuerySchema,
  WorkspaceExportSchema,
  DeleteAccountRequestSchema,
  CampaignListResponseSchema,
  CampaignListQuerySchema,
  CampaignResponseSchema,
  CreateCampaignRequestSchema,
  UpdateCampaignRequestSchema,
  CampaignTransitionRequestSchema,
  CampaignRecipientListResponseSchema,
  CampaignRecipientResponseSchema,
  CampaignRecipientListQuerySchema,
  CampaignRecipientRemoveRequestSchema,
  CampaignOutcomeRequestSchema,
  CampaignOutcomeResponseSchema,
  WhatsAppLinkResponseSchema,
  CampaignAuditResponseSchema,
} from './schemas.js';

export type RouteDefinition = Readonly<{
  operationId: string;
  module:
    | 'health'
    | 'auth'
    | 'workspace'
    | 'customers'
    | 'customerImports'
    | 'campaigns'
    | 'today'
    | 'bookings'
    | 'results'
    | 'reviews'
    | 'openapi';
  method: 'get' | 'post' | 'patch' | 'delete';
  path: string;
  auth: 'public' | 'session' | 'csrf';
  request?: z.ZodType;
  query?: z.ZodType;
  responses: Readonly<Record<number, z.ZodType>>;
}>;

export const routeRegistry = [
  {
    operationId: 'healthLive',
    module: 'health',
    method: 'get',
    path: '/api/v1/health/live',
    auth: 'public',
    responses: { 200: z.object({ status: z.literal('ok') }) },
  },
  {
    operationId: 'healthReady',
    module: 'health',
    method: 'get',
    path: '/api/v1/health/ready',
    auth: 'public',
    responses: { 200: z.object({ status: z.string() }), 503: ErrorResponseSchema },
  },
  {
    operationId: 'csrf',
    module: 'auth',
    method: 'get',
    path: '/api/v1/auth/csrf',
    auth: 'public',
    responses: { 200: CsrfResponseSchema },
  },
  {
    operationId: 'register',
    module: 'auth',
    method: 'post',
    path: '/api/v1/auth/register',
    auth: 'csrf',
    request: RegisterRequestSchema,
    responses: {
      201: RegisterResponseSchema,
      400: ErrorResponseSchema,
    },
  },
  {
    operationId: 'signIn',
    module: 'auth',
    method: 'post',
    path: '/api/v1/auth/sign-in',
    auth: 'csrf',
    request: SignInRequestSchema,
    responses: {
      200: RegisterResponseSchema,
      401: ErrorResponseSchema,
    },
  },
  {
    operationId: 'signOut',
    module: 'auth',
    method: 'post',
    path: '/api/v1/auth/sign-out',
    auth: 'csrf',
    responses: { 204: z.null(), 401: ErrorResponseSchema },
  },
  {
    operationId: 'requestPasswordReset',
    module: 'auth',
    method: 'post',
    path: '/api/v1/auth/password-reset-requests',
    auth: 'csrf',
    request: PasswordResetRequestSchema,
    responses: { 202: PasswordResetRequestResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'completePasswordReset',
    module: 'auth',
    method: 'post',
    path: '/api/v1/auth/password-resets',
    auth: 'csrf',
    request: PasswordResetCompleteRequestSchema,
    responses: {
      200: PasswordResetCompleteResponseSchema,
      400: ErrorResponseSchema,
      401: ErrorResponseSchema,
    },
  },
  {
    operationId: 'session',
    module: 'auth',
    method: 'get',
    path: '/api/v1/session',
    auth: 'session',
    responses: {
      200: z.object({ userId: z.string(), workspaceId: z.string() }),
      401: ErrorResponseSchema,
    },
  },
  {
    operationId: 'getWorkspace',
    module: 'workspace',
    method: 'get',
    path: '/api/v1/workspace',
    auth: 'session',
    responses: { 200: WorkspaceResponseSchema, 401: ErrorResponseSchema },
  },
  {
    operationId: 'updateWorkspace',
    module: 'workspace',
    method: 'patch',
    path: '/api/v1/workspace',
    auth: 'csrf',
    request: WorkspaceSettingsPatchSchema,
    responses: { 200: WorkspaceResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'listCustomers',
    module: 'customers',
    method: 'get',
    path: '/api/v1/customers',
    auth: 'session',
    responses: {
      200: z.object({ items: z.array(CustomerResponseSchema), nextCursor: z.string().nullable() }),
      401: ErrorResponseSchema,
    },
  },
  {
    operationId: 'getCustomer',
    module: 'customers',
    method: 'get',
    path: '/api/v1/customers/{customerId}',
    auth: 'session',
    responses: { 200: CustomerResponseSchema, 404: ErrorResponseSchema },
  },
  {
    operationId: 'getCustomerDetail',
    module: 'customers',
    method: 'get',
    path: '/api/v1/customers/{customerId}/detail',
    auth: 'session',
    responses: { 200: CustomerDetailResponseSchema, 404: ErrorResponseSchema },
  },
  {
    operationId: 'createCustomer',
    module: 'customers',
    method: 'post',
    path: '/api/v1/customers',
    auth: 'csrf',
    request: CreateCustomerRequestSchema,
    responses: { 201: CustomerResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'updateCustomer',
    module: 'customers',
    method: 'patch',
    path: '/api/v1/customers/{customerId}',
    auth: 'csrf',
    request: UpdateCustomerRequestSchema,
    responses: { 200: CustomerResponseSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
  },
  {
    operationId: 'recordInteraction',
    module: 'customers',
    method: 'post',
    path: '/api/v1/customers/{customerId}/interactions',
    auth: 'csrf',
    request: CreateInteractionRequestSchema,
    responses: { 201: InteractionResponseSchema, 404: ErrorResponseSchema },
  },
  {
    operationId: 'recordConsent',
    module: 'customers',
    method: 'post',
    path: '/api/v1/customers/{customerId}/consents',
    auth: 'csrf',
    request: RecordConsentRequestSchema,
    responses: {
      201: z.object({
        id: z.string(),
        channel: z.string(),
        decision: z.string(),
        capturedAt: z.string(),
      }),
      404: ErrorResponseSchema,
    },
  },
  {
    operationId: 'previewCustomerImport',
    module: 'customerImports',
    method: 'post',
    path: '/api/v1/customer-imports/preview',
    auth: 'csrf',
    request: CustomerImportPreviewRequestSchema,
    responses: { 200: CustomerImportPreviewResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'commitCustomerImport',
    module: 'customerImports',
    method: 'post',
    path: '/api/v1/customer-imports/{importId}/commit',
    auth: 'csrf',
    request: CustomerImportCommitRequestSchema,
    responses: { 200: CustomerImportCommitResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'listCampaigns',
    module: 'campaigns',
    method: 'get',
    path: '/api/v1/campaigns',
    auth: 'session',
    query: CampaignListQuerySchema,
    responses: { 200: CampaignListResponseSchema, 401: ErrorResponseSchema },
  },
  {
    operationId: 'createCampaign',
    module: 'campaigns',
    method: 'post',
    path: '/api/v1/campaigns',
    auth: 'csrf',
    request: CreateCampaignRequestSchema,
    responses: { 201: CampaignResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'getCampaign',
    module: 'campaigns',
    method: 'get',
    path: '/api/v1/campaigns/{campaignId}',
    auth: 'session',
    responses: { 200: CampaignResponseSchema, 404: ErrorResponseSchema },
  },
  {
    operationId: 'getCampaignAudit',
    module: 'campaigns',
    method: 'get',
    path: '/api/v1/campaigns/{campaignId}/audit',
    auth: 'session',
    responses: { 200: CampaignAuditResponseSchema, 404: ErrorResponseSchema },
  },
  {
    operationId: 'updateCampaign',
    module: 'campaigns',
    method: 'patch',
    path: '/api/v1/campaigns/{campaignId}',
    auth: 'csrf',
    request: UpdateCampaignRequestSchema,
    responses: { 200: CampaignResponseSchema, 409: ErrorResponseSchema, 412: ErrorResponseSchema },
  },
  {
    operationId: 'transitionCampaign',
    module: 'campaigns',
    method: 'post',
    path: '/api/v1/campaigns/{campaignId}/transition',
    auth: 'csrf',
    request: CampaignTransitionRequestSchema,
    responses: { 200: CampaignResponseSchema, 409: ErrorResponseSchema, 412: ErrorResponseSchema },
  },
  {
    operationId: 'refreshCampaignRecipients',
    module: 'campaigns',
    method: 'post',
    path: '/api/v1/campaigns/{campaignId}/recipients/refresh',
    auth: 'csrf',
    request: z.object({ version: z.number().int().positive() }),
    responses: {
      200: CampaignRecipientListResponseSchema,
      409: ErrorResponseSchema,
      412: ErrorResponseSchema,
    },
  },
  {
    operationId: 'listCampaignRecipients',
    module: 'campaigns',
    method: 'get',
    path: '/api/v1/campaigns/{campaignId}/recipients',
    auth: 'session',
    query: CampaignRecipientListQuerySchema,
    responses: { 200: CampaignRecipientListResponseSchema, 404: ErrorResponseSchema },
  },
  {
    operationId: 'removeCampaignRecipient',
    module: 'campaigns',
    method: 'post',
    path: '/api/v1/campaigns/{campaignId}/recipients/{recipientId}/remove',
    auth: 'csrf',
    request: CampaignRecipientRemoveRequestSchema,
    responses: {
      200: CampaignRecipientResponseSchema,
      409: ErrorResponseSchema,
      412: ErrorResponseSchema,
    },
  },
  {
    operationId: 'recordCampaignOutcome',
    module: 'campaigns',
    method: 'post',
    path: '/api/v1/campaigns/{campaignId}/recipients/{recipientId}/outcome',
    auth: 'csrf',
    request: CampaignOutcomeRequestSchema,
    responses: { 200: CampaignOutcomeResponseSchema, 409: ErrorResponseSchema },
  },
  {
    operationId: 'getCampaignWhatsAppLink',
    module: 'campaigns',
    method: 'get',
    path: '/api/v1/campaigns/{campaignId}/recipients/{recipientId}/whatsapp-link',
    auth: 'session',
    responses: { 200: WhatsAppLinkResponseSchema, 409: ErrorResponseSchema },
  },
  {
    operationId: 'exportCampaignRecipients',
    module: 'campaigns',
    method: 'get',
    path: '/api/v1/campaigns/{campaignId}/recipients.csv',
    auth: 'session',
    responses: { 200: z.string(), 404: ErrorResponseSchema },
  },
  {
    operationId: 'getToday',
    module: 'today',
    method: 'get',
    path: '/api/v1/today',
    auth: 'session',
    responses: { 200: TodayResponseSchema, 401: ErrorResponseSchema },
  },
  {
    operationId: 'createBooking',
    module: 'bookings',
    method: 'post',
    path: '/api/v1/bookings',
    auth: 'csrf',
    request: CreateBookingRequestSchema,
    responses: { 201: BookingResponseSchema, 409: ErrorResponseSchema },
  },
  {
    operationId: 'listBookings',
    module: 'bookings',
    method: 'get',
    path: '/api/v1/bookings',
    auth: 'session',
    responses: {
      200: z.object({ items: z.array(BookingResponseSchema) }),
      401: ErrorResponseSchema,
    },
  },
  {
    operationId: 'updateBookingStatus',
    module: 'bookings',
    method: 'patch',
    path: '/api/v1/bookings/{bookingId}/status',
    auth: 'csrf',
    request: UpdateBookingStatusRequestSchema,
    responses: { 200: BookingResponseSchema, 404: ErrorResponseSchema, 409: ErrorResponseSchema },
  },
  {
    operationId: 'getResults',
    module: 'results',
    method: 'get',
    path: '/api/v1/results',
    auth: 'session',
    query: ResultsQuerySchema,
    responses: { 200: ResultsResponseSchema, 401: ErrorResponseSchema },
  },
  {
    operationId: 'exportResultsCsv',
    module: 'results',
    method: 'get',
    path: '/api/v1/results.csv',
    auth: 'session',
    query: ResultsQuerySchema,
    responses: { 200: z.string(), 401: ErrorResponseSchema },
  },
  {
    operationId: 'listReviews',
    module: 'reviews',
    method: 'get',
    path: '/api/v1/reviews',
    auth: 'session',
    query: ReviewListQuerySchema,
    responses: { 200: ReviewListResponseSchema, 401: ErrorResponseSchema },
  },
  {
    operationId: 'createReview',
    module: 'reviews',
    method: 'post',
    path: '/api/v1/reviews',
    auth: 'csrf',
    request: CreateReviewRequestSchema,
    responses: { 201: ReviewResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'changeReviewResponse',
    module: 'reviews',
    method: 'patch',
    path: '/api/v1/reviews/{reviewId}/response',
    auth: 'csrf',
    request: ReviewResponseActionSchema,
    responses: { 200: ReviewResponseSchema, 400: ErrorResponseSchema, 404: ErrorResponseSchema },
  },
  {
    operationId: 'previewReviewImport',
    module: 'reviews',
    method: 'post',
    path: '/api/v1/review-imports/preview',
    auth: 'csrf',
    request: ReviewImportPreviewRequestSchema,
    responses: { 200: ReviewImportPreviewResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'commitReviewImport',
    module: 'reviews',
    method: 'post',
    path: '/api/v1/review-imports/{importId}/commit',
    auth: 'csrf',
    request: ReviewImportCommitRequestSchema,
    responses: { 200: ReviewImportCommitResponseSchema, 400: ErrorResponseSchema },
  },
  {
    operationId: 'exportWorkspace',
    module: 'workspace',
    method: 'get',
    path: '/api/v1/workspace/export',
    auth: 'session',
    responses: { 200: WorkspaceExportSchema, 401: ErrorResponseSchema },
  },
  {
    operationId: 'deleteWorkspaceAccount',
    module: 'workspace',
    method: 'delete',
    path: '/api/v1/workspace/account',
    auth: 'csrf',
    request: DeleteAccountRequestSchema,
    responses: { 204: z.null(), 400: ErrorResponseSchema, 401: ErrorResponseSchema },
  },
  {
    operationId: 'openapi',
    module: 'openapi',
    method: 'get',
    path: '/api/v1/openapi.json',
    auth: 'public',
    responses: { 200: z.record(z.string(), z.unknown()) },
  },
] satisfies readonly RouteDefinition[];

export type RegisteredOperationId = (typeof routeRegistry)[number]['operationId'];
